# Probar Modelos con PyCaret (TEMPLATE - Prof. Inofuente)

# Paso 1: Cargamos Pycaret y un Dataset

In [1]:
import pycaret
pycaret.__version__

'3.3.2'

In [2]:
from pycaret.datasets import get_data
Datos_traffic = get_data(dataset = 'diabetes') #Aquí cambias el Dataset

,Number of times pregnant,Plasma glucose concentration a 2 hours in an oral glucose tolerance test,Diastolic blood pressure (mm Hg),Triceps skin fold thickness (mm),2-Hour serum insulin (mu U/ml),Body mass index (weight in kg/(height in m)^2),Diabetes pedigree function,Age (years),Class variable
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

# Paso 2: Importar las Regresiones de Pycaret y Crear el Objeto

In [3]:
from pycaret.regression import *

In [4]:
# import RegressionExperiment and init the class
from pycaret.regression import RegressionExperiment
ExperimentoRegresion = RegressionExperiment() #Instanciamos la clase

# Paso 3: Configurar el Experimento u Objeto

In [5]:
# init setup on exp
ExperimentoRegresion.setup(Datos_traffic, target = 'Class variable', session_id = 123)
                                          #Coloco la etiqueta de mi Target, en este caso el Volumen del Tráfico

Usamos la VALIDACIÓN CRUZADA KFold, cuya técnica divide el conjunto de datos en K partes (o folds). En cada iteración del proceso, se utiliza uno de los folds como conjunto de prueba y los otros K-1 como conjunto de entrenamiento. Esto se repite K veces.

# Paso 4: Entrenamos y Comparamos los Modelos

In [25]:
#Comparamos los Modelos usando POO
MejorModelo = ExperimentoRegresion.compare_models()

### *Resolver*
#### 1. ¿Cuál es el mejor modelo y por qué? Justificar. ¿Qué significa cada métrica?

In [7]:
print(MejorModelo)

ExtraTreesRegressor(n_jobs=-1, random_state=123)

In [8]:
ExperimentoRegresion.models()

,Name,Reference,Turbo
ID,,,
lr,Linear Regression,sklearn.linear_model._base.LinearRegression,True
lasso,Lasso Regression,sklearn.linear_model._coordinate_descent.Lasso,True
ridge,Ridge Regression,sklearn.linear_model._ridge.Ridge,True
en,Elastic Net,sklearn.linear_model._coordinate_descent.Elast...,True
lar,Least Angle Regression,sklearn.linear_model._least_angle.Lars,True
llar,Lasso Least Angle Regression,sklearn.linear_model._least_angle.LassoLars,True
omp,Orthogonal Matching Pursuit,sklearn.linear_model._omp.OrthogonalMatchingPu...,True
br,Bayesian Ridge,sklearn.linear_model._bayes.BayesianRidge,True
ard,Automatic Relevance Determination,sklearn.linear_model._bayes.ARDRegression,False
par,Passive Aggressive Regressor,sklearn.linear_model._passive_aggressive.Passi...,True
ransac,Random Sample Consensus,sklearn.linear_model._ransac.RANSACRegressor,False
tr,TheilSen Regressor,sklearn.linear_model._theil_sen.TheilSenRegressor,False
huber,Huber Regressor,sklearn.linear_model._huber.HuberRegressor,True
kr,Kernel Ridge,sklearn.kernel_ridge.KernelRidge,False
svm,Support Vector Regression,sklearn.svm._classes.SVR,False
knn,K Neighbors Regressor,sklearn.neighbors._regression.KNeighborsRegressor,True
dt,Decision Tree Regressor,sklearn.tree._classes.DecisionTreeRegressor,True
rf,Random Forest Regressor,sklearn.ensemble._forest.RandomForestRegressor,True
et,Extra Trees Regressor,sklearn.ensemble._forest.ExtraTreesRegressor,True
ada,AdaBoost Regressor,sklearn.ensemble._weight_boosting.AdaBoostRegr...,True
gbr,Gradient Boosting Regressor,sklearn.ensemble._gb.GradientBoostingRegressor,True
mlp,MLP Regressor,sklearn.neural_network._multilayer_perceptron....,False
lightgbm,Light Gradient Boosting Machine,lightgbm.sklearn.LGBMRegressor,True
dummy,Dummy Regressor,sklearn.dummy.DummyRegressor,True

## Respecto del MSE

In [9]:
compare_tree_models = ExperimentoRegresion.compare_models(include = ['et', 'rf', 'ridge', 'lr', 'lar'])

### *Resolver*
#### 2. ¿Por qué escogiste estos 7 modelos en la lista de include?. Si deseas puedes ayudarte del ordenamiento

# Paso 4 (Opcional):Ordenamiento de los mejores modelos respecto de una métrica

In [10]:
Mejores_Modelos_TOP3_MSE = ExperimentoRegresion.compare_models(sort = 'MSE', n_select = 3)

# Paso 5: Tuneamos los hypermarámetros del Mejor Modelo

In [11]:
# Ahora seleccionas uno de esos modelos para tunearlo
MejorModelo = Mejores_Modelos_TOP3_MSE[0]  # Selecciona el mejor de los tres

In [12]:
MejorModelo

ExtraTreesRegressor(n_jobs=-1, random_state=123)

In [13]:
MejorModelo_Tuneado = ExperimentoRegresion.tune_model(estimator=MejorModelo, n_iter=10)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

### *Resolver*
#### 3. ¿El mejor modelo tuneado ha tenido mejores valores de salida respecto a las métrica que el mejor modelo sin tunear?. Si tuvo o no, justifica tu respuesta.

# Paso 6: Finalizar Modelo

In [14]:
Modelo_Final = ExperimentoRegresion.finalize_model(estimator = MejorModelo_Tuneado) #Escoger el MejorModelo o MejorModelo_Tuneado dependiendo de tu respuesta de arriba.

In [15]:
Modelo_Final

Pipeline(memory=Memory(location=None),
         steps=[('numerical_imputer',
                 TransformerWrapper(include=['Number of times pregnant',
                                             'Plasma glucose concentration a 2 '
                                             'hours in an oral glucose '
                                             'tolerance test',
                                             'Diastolic blood pressure (mm Hg)',
                                             'Triceps skin fold thickness (mm)',
                                             '2-Hour serum insulin (mu U/ml)',
                                             'Body mass index (weight in '
                                             'kg/(height in m)^2)',
                                             'Diabetes pedigree function',
                                             'Age (years)'],
                                    transformer=SimpleImputer())),
                ('categorical_imputer',
                 TransformerWrapper(include=[],
                                    transformer=SimpleImputer(strategy='most_frequent'))),
                ('clean_column_names',
                 TransformerWrapper(transformer=CleanColumnNames())),
                ('actual_estimator',
                 ExtraTreesRegressor(n_jobs=-1, random_state=123))])

# Paso 7: Guardar Modelo

### Guardamos el Pipeline Completo de PyCaret

In [18]:
ExperimentoRegresion.save_model(model = Modelo_Final, model_name = '../models/Pycaret/Pipeline_Completo_Best_Model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['Number of times pregnant',
                                              'Plasma glucose concentration a 2 '
                                              'hours in an oral glucose '
                                              'tolerance test',
                                              'Diastolic blood pressure (mm Hg)',
                                              'Triceps skin fold thickness (mm)',
                                              '2-Hour serum insulin (mu U/ml)',
                                              'Body mass index (weight in '
                                              'kg/(height in m)^2)',
                                              'Diabetes pedigree function',
                                              'Age (years)'],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=[],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('clean_column_names',
                  TransformerWrapper(transformer=CleanColumnNames())),
                 ('actual_estimator',
                  ExtraTreesRegressor(n_jobs=-1, random_state=123))]),
 '../models/Pycaret/Pipeline_Completo_Best_Model.pkl')

### Guardamos solamente el estimador, sin ningún paso de preprocesamiento

In [20]:
import joblib
joblib.dump(MejorModelo_Tuneado, '../models/Pycaret/Best_Model.pkl')

['../models/Pycaret/Best_Model.pkl']

# Paso 8: Cargar Modelo (Hasta aquí entra la Tarea y la Evaluación)

In [24]:
Modelo_Cargado_desde_Disco = ExperimentoRegresion.load_model('../models/Pycaret/Best_Model')

Transformation Pipeline and Model Successfully Loaded